stages: # List of stages for jobs, and their order of execution*
    - build

cache:
    paths:
        - /build

build-deploy-job:
    stage: build
    image: alpine:latest
    only:
        refs:
            - main
    script:
        - apk add --update npm
        - npm install
        - npm run build
        - echo "Compile complete."

#lint-job:
#    stage: lint
#    script:
#        - apk add --update npm
#        - npm install
#        - npm run prettier
