stages:          # List of stages for jobs, and their order of execution*
    - build
    - test
    - deploy

cache:
  paths:
    - /build

build-job:    
    stage: build
    image: ubuntu:latest
    only:
        refs:
            - main
    script:
        - npm install
        - npm run build
        - echo "Compile complete."

unit-test-job:  
    stage: test
    image: ubuntu:latest
    only:
        refs:
            - main
    script:
        - npm install
        - npm run test:unit

#deploy-job:     
#    stage: deploy
#    script:
#        - echo "Deploying application..."
#        - echo "Application successfully deployed."