stages: # List of stages for jobs, and their order of execution*
    - test
    - build

cache:
    paths:
        - /dist


test-job:
    stage: test
    image: ubuntu:latest
    only:
        refs:
            - main
            - merge_requests
    script:
        - apt update
        - apt install -y curl
        - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
        - apt update
        - apt install -y nodejs
        - apt install npm -y
        - npm install
        - npm run test

build-job:
    stage: build
    image: ubuntu:latest
    only:
        refs:
            - main
    script:
        - apt update
        - apt install rsync -y
        - apt install openssh-client -y
        - mkdir ~/.ssh
        - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        - touch ~/.ssh/id_rsa
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - echo $'' >> ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa # Required permission by ssh
        - echo "$FRONTEND_ENV" > .env
        - ssh eposkk@35.228.176.246 echo "Hi, this is a test"
        - rsync --archive --delete --exclude='.git' --exclude='node_modules' . eposkk@35.228.176.246:frontend
        - ssh eposkk@35.228.176.246 make -C frontend deploy
